uint8 Veh_fb_FaultLevel
bool Veh_fb_AutoCANCtrlCmd
bool Veh_fb_AutoIOCANCmd

bool Veh_fb_EPSDisOnline
bool Veh_fb_EPSfault

bool Veh_fb_EPSMosfetOT

bool Veh_fb_EPSWarning

bool Veh_fb_EPSDisWork

bool Veh_fb_EPSOverCurrent

bool Veh_fb_STReserve

bool Veh_fb_EHBecuFault

bool Veh_fb_EHBDisOnline

bool Veh_fb_EHBWorkModelFault

bool Veh_fb_EHBDisEn

bool Veh_fb_EHBAnguleFault

bool Veh_fb_EHBOT

bool Veh_fb_EHBPowerFault

bool Veh_fb_EHBsensorAbnomal

bool Veh_fb_EHBMotorFault

bool Veh_fb_EHBOilPressSensorFault

bool Veh_fb_EHBOilFault

bool Veh_fb_BraReserve

bool Veh_fb_DrvMCUDisOnline

bool Veh_fb_DrvMCUOT

bool Veh_fb_DrvMCUOV

bool Veh_fb_DrvMCUUV

bool Veh_fb_DrvMCUShort

bool Veh_fb_DrvMCUScram

bool Veh_fb_DrvMCUHall

bool Veh_fb_DrvMCUMOSFEF

bool Veh_fb_DrvReserve

bool Veh_fb_AUXBMSDisOnline

bool Veh_fb_AuxScram

bool Veh_fb_AuxRemoteClose

bool Veh_fb_AuxRemoteDisOnline

bool Veh_fb_AuxReserve

